#!/bin/bash

wallpaper="$(realpath "$1")"

mime_type=`file --mime-type -b "$wallpaper"`
if [[ ! "$mime_type" == image/* ]]; then
	echo "Invalid image"
	exit 1
fi

properties=$(xfconf-query -c xfce4-desktop -p /backdrop -l | grep -e "screen.*/monitor.*image-path$" -e "screen.*/monitor.*/last-image$")

for property in $properties; do
	xfconf-query -c xfce4-desktop -p $property -s "$wallpaper"
done
